name: Build and Test
on: [push]
jobs:
  - name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Mock Build
        run: echo 'Build successful!'
        shell: bash